name: develop
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch-gpu=1.10.1
  - torchvision=0.11.2
  - cudatoolkit=11.3
  - ca-certificates
  - openssl
  - ipykernel
  - opencv
  - pandas
  - pyyaml
  - scikit-image
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - torchinfo
  - certifi
  - hydra-core
  - black # code formatting
  - isort # import sorting
  - flake8 # code analysis
  - mypy
  - rich # beautiful text formatting in terminal
  - pip:
      - colorlog
      - hydra-colorlog
      - hydra-optuna-sweeper
