# @package _global_

defaults:
  - _self_
  - datamodule: cifar.yaml
  - model: resnet.yaml
  - optimizer: adam.yaml
  - scheduler: steplr.yaml
  - log_dir: default.yaml

  - experiment: null

  - debug: null

  - hparams_search: null

  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}
data_dir: ${original_work_dir}/data/

seed: 9999

num_epochs: 3
gpu: 1

train: True
test: True

name: "default"

pretrain_ckpt_path: null