_target_: src.datamodules.cifar.CIFARDataModule

data_source: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
train_val_test_split: [45_000, 5_000, 10_000]
num_workers: 4
pin_memory: True